name: Test Run

on:
  push:
    branches:
      - main

jobs:
  mac:
    name: "macOS x86_64"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest

      - name: Install Qt, LibArchive and PkgConfig
        run: |
          brew install qt@5 libarchive pkg-config gnu-sed

      - name: Patch libarchive homebrew
        run: |
          gsed -i '/Requires.private: iconv/d' /usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc
          cat /usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc

      - name: Init Submodule
        run: |
          git submodule init
          git submodule update

      - name: Build and Test
        id: macos_build
        run: |
          mkdir build
          cd build
          export Qt5_DIR=$(brew --prefix qt@5)
          export QT_DIR=$(brew --prefix qt@5)
          cmake -DLIBARCHIVE_PKG_CONFIG=$(brew --prefix libarchive)/lib/pkgconfig/ ..
          cmake --build . --config release
          echo ""
          echo ""
          echo "Test Program Output:: "
          ./MyCoolApplication
